# Generated by Django 4.2.4 on 2023-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlogic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='这是name',
        ),
        migrations.AddField(
            model_name='test',
            name='testa',
            field=models.IntegerField(blank=True, default=0, help_text='这是一个测试', verbose_name='这是name'),
        ),
    ]
