# Generated by Django 4.2.4 on 2023-08-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlogic', '0002_remove_test_这是name_test_testa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': '测试表'},
        ),
        migrations.AddField(
            model_name='test',
            name='botname',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='botname'),
        ),
    ]
